# Generated by Django 6.0.4 on 2026-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_categoria_alter_producto_cantidad_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
